name: Build and Test

on:
  push:
    paths: 
      - 'src/exercise.py'

jobs:
  
  get_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with: 
        repository: CS-1030/test-scripts          
        token: ${{ secrets.PAT }}
        path: temp
    - run: cat temp/lesson7/test_exercise.py > tests/test_exercise.py
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'tests/test_exercise.py --force'
        message: 'Automated test retrieval'
        author_name: ${{ github.repository_owner }}
     
  test_and_comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt   
    - name: Test student program
      run: python3 -m pytest >> .github/ISSUE_TEMPLATE/test-failure.md
    - name: Failure message
      if: failure()
      uses: machine-learning-apps/pr-comment@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .github/ISSUE_TEMPLATE/test-failure.md    
    - name: Lint student program
      run: flake8 src/exercise.py --max-line-length=79
    - name: Success message
      uses: machine-learning-apps/pr-comment@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .github/ISSUE_TEMPLATE/test-success.md
